<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>kartoshka-youtuber</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Version>6.9.2</Version>
    <AssemblyVersion>6.9.2.0</AssemblyVersion>
    <FileVersion>6.9.2.0</FileVersion>
    <Product>Kartoshka Youtuber</Product>
    <Company>NaderB</Company>
    <Authors>NaderB</Authors>
    <Copyright>Copyright (c) 2026 Nader Barakat</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>

</Project>
